version: '2.1'

services:
  static:
    build: ./static
    image: btcproof.info/static
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - cert-server
    networks:
      - client-server
  cert-server:
    build: ./cert-server
    image: btcproof.info/cert-server
    restart: on-failure
    networks:
      - client-server
networks:
  client-server:
    driver: bridge